import java.io.FileNotFoundException;
import java.util.Scanner;

import static CodeSavannaUtils.coreUtils.*;
import static CodeSavannaUtils.fileUtils.*;
import static CodeSavannaUtils.arrayUtils.*;
import static CodeSavannaUtils.printUtils.*;

public class CodeSavanna {

    /**
     * Displays a file menu to the user, allowing them to list the contents of specific files
     * (animals, clients, and interactions) or return to the previous menu.
     *
     * @param animals      a 2D array representing the contents of the 'animals' file
     * @param clients      a 2D array representing the contents of the 'clients' file
     * @param interactions a 2D array representing the contents of the 'interacoes' file
     */
    static void printFileMenu(String[][] animals, String[][] clients, String[][] interactions) {
        Scanner input = new Scanner(System.in);
        String option;

        do {
            printResultHeader("CodeSavanna - Menu Ficheiros");

            System.out.println("1 - Listar conteúdo do ficheiro 'animais'");
            System.out.println("2 - Listar conteúdo do ficheiro 'clientes'");
            System.out.println("3 - Listar conteúdo do ficheiro 'interacoes'");
            System.out.println("0 - Voltar");

            System.out.print("\nOpção: ");
            option = input.next();

            switch (option) {
                case "1":
                    printResultHeader("Listar conteúdo do ficheiro 'animais'");
                    printMatrix(animals);
                    break;
                case "2":
                    printResultHeader("Listar conteúdo do ficheiro 'clientes'");
                    printMatrix(clients);
                    break;
                case "3":
                    printResultHeader("Listar conteúdo do ficheiro 'interacoes'");
                    printMatrix(interactions);
                    break;
                case "0":
                    break;
                default:
                    System.out.println("Opção inválida!");
                    break;
            }
        } while (!option.equals("0"));
    }

    /**
     * Prints statistics of interactions by category such as "VISITA", "ESPETACULO",
     * "ALIMENTACAO", and "APADRINHAMENTO" based on the provided data.
     *
     * @param interactions a 2D array where each row represents an interaction and
     *                     each column contains specific details about that interaction. The third
     *                     column (index 2) is used to determine the interaction category.
     */
    static void printInteractionsStats(String[][] interactions) {
        int visitCount = countValueInColumn(interactions, 2, "VISITA");
        int showCount = countValueInColumn(interactions, 2, "ESPETACULO");
        int feedCount = countValueInColumn(interactions, 2, "ALIMENTACAO");
        int sponsorCount = countValueInColumn(interactions, 2, "APADRINHAMENTO");

        printResultHeader("Estatísticas gerais de interações");

        System.out.printf("%-21s", "Total de interações:");
        System.out.println(interactions.length - 1); // Excluimos a linha com os cabeçalhos

        System.out.printf("%-21s", "APADRINHAMENTO:");
        System.out.println(visitCount);

        System.out.printf("%-21s", "ESPETACULO:");
        System.out.println(showCount);

        System.out.printf("%-21s", "ALIMENTACAO:");
        System.out.println(feedCount);

        System.out.printf("%-21s", "APADRINHAMENTO:");
        System.out.println(sponsorCount);

        printResultFooter();
    }

    /**
     * Prints statistics of income generated by different types of interactions.
     * The method calculates the income for specified interaction types (VISITA, ESPETACULO,
     * ALIMENTACAO, and APADRINHAMENTO) and displays the totals along with a formatted header
     * and footer.
     *
     * @param interactions A 2D array where each element represents an interaction. Each interaction
     *                     contains multiple fields, where the third field (index 2) corresponds
     *                     to the value associated with the interaction type.
     */
    static void printInteractionsIncomeStats(String[][] interactions) {
        double visitIncome = sumValueByCriteria(interactions, 2, "VISITA");
        double showIncome = sumValueByCriteria(interactions, 2, "ESPETACULO");
        double feedIncome = sumValueByCriteria(interactions, 2, "ALIMENTACAO");
        double sponsorIncome = sumValueByCriteria(interactions, 2, "APADRINHAMENTO");
        double totalIncome = visitIncome + showIncome + feedIncome + sponsorIncome;

        printResultHeader("Receita total por tipo de interação");

        System.out.printf("%-19s", "Total de receitas:");
        System.out.println(totalIncome);

        System.out.printf("%-19s", "VISITA:");
        System.out.println("VISITA: " + visitIncome);

        System.out.printf("%-19s", "ESPETACULO:");
        System.out.println("ESPETACULO: " + showIncome);

        System.out.printf("%-19s", "ALIMENTACAO:");
        System.out.println("ALIMENTACAO: " + feedIncome);

        System.out.printf("%-19s", "APADRINHAMENTO:");
        System.out.println("APADRINHAMENTO: " + sponsorIncome);

        printResultFooter();
    }

    /**
     * Prints the details of the most popular animal based on the number of interactions.
     * <p>
     * This method identifies the animal with the highest number of interactions
     * from the given data and displays its name, species, habitat, and total interactions.
     * It assumes that the input data includes headers that must be skipped during processing.
     *
     * @param animals      a 2D array where each row represents an animal and its attributes,
     *                     with the first row containing headers
     * @param interactions a 2D array where each row represents interaction details,
     *                     with the first row containing headers
     */
    static void printMostPopularAnimal(String[][] animals, String[][] interactions) {
        int[] animalInteractions = new int[animals.length - 1]; // Salta a linha do cabeçalho

        int countIndex = 0;
        for (int i = 1; i < animals.length; i++) { // Salta a linha de cabeçalho
            int interactionCount = 0;
            for (int j = 1; j < interactions.length; j++) { // Salta a linha do cabeçalho
                if (animals[i][0].equals(interactions[j][3])) {
                    interactionCount++;
                }
            }
            animalInteractions[countIndex++] = interactionCount;
        }

        int maxInteractions = animalInteractions[0];
        int mostPopularIndex = 0;
        for (int i = 1; i < animalInteractions.length; i++) {
            if (animalInteractions[i] > maxInteractions) {
                maxInteractions = animalInteractions[i];
                mostPopularIndex = i + 1; // Adiciona a linha do cabeçalho
            }
        }

        printResultHeader("Animal mais popular");

        System.out.printf("%-12s", "Nome:");
        System.out.println(animals[mostPopularIndex][1]);

        System.out.printf("%-12s", "Espécie:");
        System.out.println(animals[mostPopularIndex][2]);

        System.out.printf("%-12s", "Habitat:");
        System.out.println(animals[mostPopularIndex][3]);

        System.out.printf("%-12s", "Interações:");
        System.out.println(maxInteractions);

        printResultFooter();
    }

    /**
     * Prints the top three sponsored species based on the number of sponsorships
     * and their total monthly income derived from sponsorships. The species are
     * displayed in descending order by the number of sponsorships.
     *
     * @param animals      A 2D array where each row represents an animal and its
     *                     associated data. Columns should include at least an
     *                     animal ID and the species to which the animal belongs.
     * @param interactions A 2D array representing interactions. Columns should
     *                     include interaction details such as interaction type
     *                     and the value paid for sponsorships.
     */
    static void printTopSponsoredSpecies(String[][] animals, String[][] interactions) {
        String[] species = getSpecies(animals);
        int[] sponsorCount = new int[species.length];
        double[] specieIncome = new double[species.length];

        for (int i = 0; i < species.length; i++) {
            // Para cada espécie, buscar animais
            for (int j = 1; j < animals.length; j++) {
                if (animals[j][2].equals(species[i])) {
                    // Para cada animal da espécie, buscar interações do tipo 'APADRINHAMENTO'
                    String[][] currentAnimalInteractions = filterByAnimalAndInteractionType(interactions, 3, animals[j][0], 2, "APADRINHAMENTO");
                    for (int k = 0; k < currentAnimalInteractions.length; k++) {
                        //Para cada interação do tipo 'APADRINHAMENTO' de cada animal da espécie, acumular valorPago e contar padrinhos
                        specieIncome[i] += Double.parseDouble(currentAnimalInteractions[k][5]);
                        sponsorCount[i]++;
                    }
                }
            }
        }

        int[] sortedSponsorCount = sortIntArrayDescending(sponsorCount);
        String[] sortedSpecies = sortStringArrayDescendingByReference(species, sponsorCount);
        double[] sortedSpecieIncome = sortDoubleArrayDescending(specieIncome);

        printResultHeader("Top 3 espécies mais apadrinhadas");

        // Imprimir o Top 3
        int topSponsoredToShow = 3;
        if (sortedSpecies.length < 3) {
            topSponsoredToShow = sortedSpecies.length;
        }

        for (int i = 0; i < topSponsoredToShow; i++) {
            System.out.println();
            System.out.println((i + 1) + ") " + sortedSpecies[i]);

            System.out.printf("%-23s", "No de apadrinhamentos:");
            System.out.println(sortedSponsorCount[i]);

            System.out.printf("%-23s", "Valor mensal total:");
            System.out.println(sortedSpecieIncome[i] + " €");

            printResultFooter();
        }

    }

    /**
     * Prints the list of sponsors for a specified animal. The method identifies the animal
     * through user selection, filters interactions for sponsorship information, and displays
     * the details of each sponsor including their name, email, sponsorship plan, and monthly
     * contribution.
     *
     * @param animals      The array containing information about animals, where each row represents
     *                     an animal and includes its unique identifier and additional details.
     * @param interactions The array containing interaction data, where each row represents
     *                     an interaction and includes the interaction type, client identifier,
     *                     and additional details.
     * @param clients      The array containing information about clients, where each row represents
     *                     a client and includes their unique identifier, name, email, and other details.
     */
    static void printAnimalSponsors(String[][] animals, String[][] interactions, String[][] clients) {

        String selectedAnimal = getValidAnimal(animals);
        String[][] selectedInteractions = filterByAnimalAndInteractionType(interactions, 3, selectedAnimal, 2, "APADRINHAMENTO");

        printResultHeader("Listar padrinhos de um animal");

        if (selectedInteractions.length == 0) {
            System.out.println("Não há padrinhos para este animal.");
            printResultFooter();
            return;
        }

        String animalName = findValueAtColumn(animals, 0, selectedAnimal, 1);

        System.out.println("Lista de padrinhos para o animal " + selectedAnimal + " (" + animalName + "):");

        for (int i = 0; i < selectedInteractions.length; i++) {
            String clientName = findValueAtColumn(clients, 0, selectedInteractions[i][1], 1);
            String clientEmail = findValueAtColumn(clients, 0, selectedInteractions[i][1], 3);

            System.out.println();
            System.out.printf("%-25s", "Nome do cliente:");
            System.out.println(clientName);

            System.out.printf("%-25s", "Email do cliente:");
            System.out.println(clientEmail);

            System.out.printf("%-25s", "Valor mensal pago:");
            System.out.println(selectedInteractions[i][5] + " €");

            System.out.printf("%-25s", "Plano de apadrinhamento:");
            System.out.println(selectedInteractions[i][4]);

            printResultFooter();
        }
    }

    /**
     * Prints details of the most profitable show, including its name, total revenue,
     * and information about the main animal associated with it.
     *
     * @param interactions The array containing data about various interactions, where each entry
     *                     represents details of a specific interaction in the format:
     *                     [interactionId, date, showName, animalId, revenue, ...].
     * @param animals      The array containing data about animals, where each entry represents
     *                     details of a specific animal in the format:
     *                     [animalId, animalName, species, ...].
     */
    static void printMostProfitableShow(String[][] interactions, String[][] animals) {
        String[] shows = getUniqueShows(interactions, 2, "ESPETACULO");
        double[] showsIncome = getShowsIncome(interactions, shows);
        int mostProfitableShowIndex = getMostProfitableShowIndex(showsIncome);
        String animalId = getAnimalIdFromShowName(interactions, shows[mostProfitableShowIndex]);
        String[][] animal = getMostValuableAnimal(animals, animalId);

        printResultHeader("Espetáculo mais rentável");

        System.out.printf("%-20s", "Nome do espetáculo:");
        System.out.println(shows[mostProfitableShowIndex]);

        System.out.printf("%-20s", "Receita total:");
        System.out.println(showsIncome[mostProfitableShowIndex] + " €");

        System.out.printf("%-20s", "Animal principal:");
        System.out.println();
        System.out.printf("%-11s", "- Nome:");
        System.out.println(animal[0][1]);

        System.out.printf("%-11s", "- Espécie:");
        System.out.println(animal[0][2]);

        printResultFooter();
    }

    /**
     * Prints the extinction rank of endangered animals, sorted by their total interactions and income.
     *
     * @param animals      A 2D string array containing animal data. Each row represents an animal, and columns contain
     *                     details like whether the animal is endangered, species, habitat, diet, etc.
     * @param interactions A 2D string array containing interaction data. Each row represents an interaction, and
     *                     columns contain details such as the animal involved, interaction type, income generated, etc.
     */
    static void printExtintionRank(String[][] animals, String[][] interactions) {
        String[][] extintionAnimals = filterMatrix(animals, 5, "SIM");
        int[] animalInteractions = getExtintionAnimalsInteractions(interactions, extintionAnimals);
        double[] animalIncome = getExtintionAnimalsIncomes(interactions, extintionAnimals);

        int[] sortedAnimalInteractions = sortIntArrayDescending(animalInteractions);
        String[][] sortedExtintionAnimals = sortStringMatrixAtColumnDescendingByReference(extintionAnimals, animalInteractions);
        double[] sortedAnimalIncome = sortDoubleArrayDescending(animalIncome);

        printResultHeader("Ranking de animais em perigo de extinção");

        for (int i = 0; i < sortedExtintionAnimals.length; i++) {

            System.out.println();
            System.out.println((i + 1) + ") " + sortedExtintionAnimals[i][1]);

            System.out.printf("%-20s", "Espécie:");
            System.out.println(sortedExtintionAnimals[i][2]);

            System.out.printf("%-20s", "Habitat:");
            System.out.println(sortedExtintionAnimals[i][3]);

            System.out.printf("%-20s", "Dieta:");
            System.out.println(sortedExtintionAnimals[i][4]);

            System.out.printf("%-20s", "Total de interação:");
            System.out.println(sortedAnimalInteractions[i]);

            System.out.printf("%-20s", "Total de receita:");
            System.out.println(sortedAnimalIncome[i] + " €");

            printResultFooter();
        }
    }

    /**
     * Displays habitat statistics including the number of animals, interactions,
     * and associated revenue for each habitat. It iterates over unique habitats,
     * filters animals belonging to each habitat, and calculates relevant statistics
     * such as total interactions and income.
     *
     * @param animals      A 2D array containing information about animals. Each inner array
     *                     represents an animal with attributes such as ID, name, species,
     *                     habitat, and status.
     * @param interactions A 2D array representing various interaction data. Each inner
     *                     array contains details such as interaction type, associated
     *                     animal ID, and financial statistics.
     */
    static void printHabitatStats(String[][] animals, String[][] interactions) {
        String[] habitats = getHabitats(animals);

        printResultHeader("Estatísticas por habitat");

        for (int i = 0; i < habitats.length; i++) {

            String[][] habitatAnimals = filterMatrix(animals, 3, habitats[i]);
            int habitatInteractions = getHabitatInteractions(interactions, habitatAnimals);
            double habitatIncome = getHabitatIncome(interactions, habitatAnimals);

            System.out.println();
            System.out.printf("%-19s", "Habitat:");
            System.out.println(habitats[i]);

            System.out.printf("%-19s", "Nº de animais:");
            System.out.println(habitatAnimals.length);

            System.out.printf("%-19s", "Nº de interações:");
            System.out.println(habitatInteractions);

            System.out.printf("%-19s", "Receita associada:");
            System.out.println(habitatIncome + " €");

            if (i < habitats.length - 1) {
                System.out.println("------------------");
            }
        }

        printResultFooter();
    }

    /**
     * Displays the administrative menu for managing animal-related data and statistics.
     * This method provides several functionalities, including viewing file content,
     * generating interaction statistics, determining animal popularity, and more.
     * The menu operates in a loop, allowing the administrator to perform multiple actions
     * until opting to exit.
     *
     * @param animals      A 2D array containing information about animals. Each inner array
     *                     represents an animal with attributes such as ID, name, species,
     *                     habitat, and status.
     * @param clients      A 2D array containing information about clients. Each inner array
     *                     represents a client with attributes such as ID, name, and contact details.
     * @param interactions A 2D array representing various interaction data. Each inner array
     *                     contains details such as interaction type (e.g., "SHOW" or "SPONSOR"),
     *                     associated animal ID, and other statistics.
     */
    static void adminMenu(String[][] animals, String[][] clients, String[][] interactions) {
        Scanner input = new Scanner(System.in);
        String option;

        do {
            printResultHeader("CodeSavanna - Menu ADMIN");

            System.out.println("1 - Listar conteúdo dos ficheiros");
            System.out.println("2 - Estatísticas gerais de interações");
            System.out.println("3 - Receita total por tipo de interação");
            System.out.println("4 - Animal mais popular");
            System.out.println("5 - Top 3 espécies com mais apadrinhamentos");
            System.out.println("6 - Listar padrinhos de um animal");
            System.out.println("7 - Espetáculo mais rentável");
            System.out.println("8 - Ranking de animais em perigo de extinção");
            System.out.println("9 - Estatísticas por habitat");
            System.out.println("0 - Voltar");

            System.out.print("\nOpção: ");
            option = input.next();

            switch (option) {
                case "1":
                    printFileMenu(animals, clients, interactions);
                    break;
                case "2":
                    printInteractionsStats(interactions);
                    break;
                case "3":
                    printInteractionsIncomeStats(interactions);
                    break;
                case "4":
                    printMostPopularAnimal(animals, interactions);
                    break;
                case "5":
                    printTopSponsoredSpecies(animals, interactions);
                    break;
                case "6":
                    printAnimalSponsors(animals, interactions, clients);
                    break;
                case "7":
                    printMostProfitableShow(interactions, animals);
                    break;
                case "8":
                    printExtintionRank(animals, interactions);
                    break;
                case "9":
                    printHabitatStats(animals, interactions);
                    break;
                case "0":
                    break;
                default:
                    System.out.println("Opção inválida!");
                    break;
            }
        } while (!option.equals("0"));

    }

    /**
     * Displays a catalog of animals grouped by their respective habitats.
     * The method retrieves unique habitats from the provided dataset, filters
     * the animals belonging to each habitat, and displays them in a structured format.
     *
     * @param animals A 2D array containing information about animals. Each inner array
     *                includes attributes such as an animal's ID, name, species, and habitat.
     */
    static void printAnimalsByHabitat(String[][] animals) {
        String[] habitats = getHabitats(animals);

        printResultHeader("Catálogo de animais por habitat");

        System.out.println();
        for (int i = 0; i < habitats.length; i++) {

            String[][] habitatAnimals = filterMatrix(animals, 3, habitats[i]);

            printResultSubHeader(habitats[i]);

            for (int j = 0; j < habitatAnimals.length; j++) {
                System.out.println("- " + habitatAnimals[j][1] + " (" + habitatAnimals[j][2] + ")");
            }
            System.out.println();
        }

        printResultFooter();
    }

    /**
     * Displays the activity statistics for a selected animal, including show participation
     * and feeding interactions. The method gathers relevant information by filtering
     * through the provided animals and interactions dataset and presents the findings
     * in a structured output format.
     *
     * @param animals      A 2D array containing detailed information about each animal.
     *                     Each inner array represents a single animal and typically includes
     *                     attributes such as ID, name, species, and habitat.
     * @param interactions A 2D array representing various interactions associated
     *                     with animals. Each inner array includes details such as
     *                     interaction type (e.g., "ESPETACULO" for shows, "ALIMENTACAO"
     *                     for feeding) and the ID of the associated animal.
     */
    static void printAnimalsActivities(String[][] animals, String[][] interactions) {
        String selectedAnimal = getValidAnimal(animals);
        String[][] seledtedAnimalInfo = filterMatrix(animals, 0, selectedAnimal);
        String[][] selectedAnimalShows = filterByAnimalAndInteractionType(interactions, 3, selectedAnimal, 2, "ESPETACULO");
        String[][] selectedAnimalFeed = filterByAnimalAndInteractionType(interactions, 3, selectedAnimal, 2, "ALIMENTACAO");

        printResultHeader("Atividades do animal " + seledtedAnimalInfo[0][1] + " (" + seledtedAnimalInfo[0][2] + ")");

        printIteractionStats("ESPETÁCULOS:", selectedAnimalShows);
        printIteractionStats("ALIMENTAÇÃO:", selectedAnimalFeed);

        printResultFooter();
    }

    /**
     * Facilitates a simulation of animal sponsorship by gathering user input such as names, email,
     * selected animal ID, and sponsorship amount. Based on the sponsorship value, the appropriate
     * sponsorship tier is determined and a summary of the sponsorship information is displayed.
     *
     * @param animals A 2D array containing information about animals, with each inner array representing
     *                an animal and including attributes such as ID, name, species, habitat, and status.
     */
    static void sponsorSimulation(String[][] animals) {
        String clientName = getValidString("Digite seu nome: ");
        String clientEmail = getValidEmail("Digite seu email: ");

        String selectedAnimalId = getValidAnimal(animals);
        String[][] seledtedAnimalInfo = filterMatrix(animals, 0, selectedAnimalId);

        double sponsorAmount = getValidSponsorAmount("Digite o valor do patrocínio desejado: ");
        String sponsorTier = getSponsorTier(sponsorAmount);

        printResultHeader("Apadrinhamento de um animal");
        printResultSubHeader("Resumo do apadrinhamento");

        System.out.println();
        System.out.printf("%-10s", "Padrinho:");
        System.out.println(clientName + " (" + clientEmail + ")");

        System.out.printf("%-10s", "Animal:");
        System.out.println(seledtedAnimalInfo[0][1] + " (" + seledtedAnimalInfo[0][2] + ") - " + seledtedAnimalInfo[0][3]);

        System.out.printf("%-10s", "Plano:");
        System.out.println(sponsorTier);

        System.out.printf("%-10s", "Valor:");
        System.out.println(sponsorAmount + " €/mês");

        printResultFooter();
    }

    /**
     * Plays a guessing game where the user tries to identify the species of an animal
     * based on clues provided such as its habitat, diet, and extinction risk status.
     * The game allows multiple attempts and provides feedback on each guess.
     * The user can choose to play again after each round.
     *
     * @param animals A 2D array containing information about animals including their
     *                names, species, habitats, diets, and whether they are at risk
     *                of extinction. Each inner array represents an animal with its attributes.
     */
    static void playSpecieGuess(String[][] animals) {
        Scanner input = new Scanner(System.in);

        printResultHeader("Jogo: adivinha a espécie");

        String keepPlaying;
        do {
            String[] animal = getRamdomItem(animals, 1, animals.length - 1);
            String extintionRiskMessage = getExtintionRiskMessage(animal);

            printResultSubHeader("Pistas");
            System.out.printf("%-19s", "PISTA 1 (habitat):");
            System.out.println(animal[3]);

            System.out.printf("%-19s", "PISTA 2 (dieta):");
            System.out.println("É " + animal[4]);

            System.out.printf("%-19s", "PISTA 3 (risco):");
            System.out.println(extintionRiskMessage);

            int guessCount = 0;
            boolean guessed;
            String keepTrying;
            do {
                guessCount++;
                String specieGuess = getValidString("\nQual a espécie? ");
                guessed = isGuessed(specieGuess, animal[2], guessCount);
                keepTrying = input.next().trim().toUpperCase();

            } while (!guessed && keepTrying.equalsIgnoreCase("S"));

            System.out.print("\nDeseja jogar outra vez? (S/N) ");
            keepPlaying = input.next();

        } while (keepPlaying.equalsIgnoreCase("S"));

        printResultFooter();
    }

    /**
     * Displays the client menu providing options for viewing the animal catalog,
     * checking activities of a specific animal, sponsoring an animal simulation,
     * and playing a guessing game based on animal species. The menu operates
     * in a loop until the user decides to exit.
     *
     * @param animals      A 2D array containing information about animals such
     *                     as their identifiers, names, species, habitats, and other attributes.
     * @param interactions A 2D array containing interaction-related data such as
     *                     events (e.g., shows or feedings) and their association
     *                     with specific animals.
     */
    static void clientMenu(String[][] animals, String[][] interactions) {
        Scanner input = new Scanner(System.in);
        String option;

        do {
            printResultHeader("CodeSavanna - Menu CLIENTE");

            System.out.println("1 - Ver catálogo de animais por habitat");
            System.out.println("2 - Ver atividades de um animal (espetáculos e alimentações)");
            System.out.println("3 - Simular apadrinhamento de um animal");
            System.out.println("4 - Jogo: adivinha a espécie");
            System.out.println("0 - Voltar");

            System.out.print("\nOpção: ");
            option = input.next();

            switch (option) {
                case "1":
                    printAnimalsByHabitat(animals);
                    break;
                case "2":
                    printAnimalsActivities(animals, interactions);
                    break;
                case "3":
                    sponsorSimulation(animals);
                    break;
                case "4":
                    playSpecieGuess(animals);
                    break;
                case "0":
                    break;
                default:
                    System.out.println("Opção inválida!");
                    break;
            }

        } while (!option.equals("0"));

    }

    /**
     * Displays the login menu for users and allows them to navigate based on their roles (Admin or Client).
     * Uses an input loop to interact with the user, providing options to switch between roles or exit the application.
     *
     * @param animals      A 2D array containing information about animals, their attributes, and data for interactions.
     * @param clients      A 2D array representing details about clients, including their credentials and other attributes.
     * @param interactions A 2D array representing various interaction-related data, including events and statistics.
     */
    static void loginMenu(String[][] animals, String[][] clients, String[][] interactions) {
        Scanner input = new Scanner(System.in);
        String loginOption;

        do {
            printResultHeader("CodeSavanna - Login");

            System.out.println("\nSelecione uma das opções de login abaixo:");
            System.out.println("1 - Administrador");
            System.out.println("2 - Cliente");
            System.out.println("0 - Sair");

            System.out.print("\nOpção: ");
            loginOption = input.next();

            switch (loginOption) {
                case "1":
                    if (validLogin("admin")) {
                        adminMenu(animals, clients, interactions);
                    }
                    break;
                case "2":
                    if (validLogin("client")) {
                        clientMenu(animals, interactions);
                    }
                    break;
                case "0":
                    System.out.println("Obrigado. Tenha um ótimo dia.");
                    break;
                default:
                    System.out.println("Opção inválida!");
                    break;
            }

        } while (!loginOption.equals("0"));

    }

    public static void main(String[] args) throws FileNotFoundException {
        String animalsFilePath = "files/animais.csv";
        String clientsFilePath = "files/clientes.csv";
        String interactionsFilePath = "files/interacoes.csv";

        String[][] animals = readCsv(animalsFilePath, ";");
        String[][] clients = readCsv(clientsFilePath, ";");
        String[][] interactions = readCsv(interactionsFilePath, ";");

        printWelcomeArt();

        loginMenu(animals, clients, interactions);

        printExitBoard();
    }

}
